on: [push, workflow_dispatch]

jobs:
  publish-nextjs-project-using-wrangler-action:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nextjs-project
    name: Publish to Cloudflare using wrangler action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Run a build step here if your project requires
      - name: Build command
        run: npx @cloudflare/next-on-pages@1
        
      - name: Deploy
        uses: Maximo-Guk/wrangler-action@maximo/fixup-235
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "./nextjs-project"
          command: pages deploy .vercel/output/static --project-name=demo-actions
  publish-hello-world-workers-project-using-wrangler-action:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hello-world-workers-project
    name: Publish to Cloudflare using wrangler action
    steps:
      - name: Checkout
        uses: actions/checkout@v4        
      - name: Deploy
        uses: Maximo-Guk/wrangler-action@maximo/fixup-235
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "./hello-world-workers-project"
          command: deploy src/index.ts