on: [push, workflow_dispatch]

jobs:
  publish-using-wrangler-action:
    runs-on: ubuntu-latest
    name: Publish to Cloudflare using wrangler action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Run a build step here if your project requires
      - name: Build command
        run: npx @cloudflare/next-on-pages@1
        
      - name: Deploy
        uses: Maximo-Guk/wrangler-action@maximo/fixup-235
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .vercel/output/static
